version: "3"
services:
  postgres:
      image: 'postgres:14.2'
      container_name: db_postgres
      restart: always
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: secret
        POSTGRES_PASSWORD: secret
        # POSTGRES_DB: users
      volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: